### ISSUE TITLE
Wrong error-message when Compass-URL does not exist

### ISSUE THREAD

**Issue by fritsvp** [Iperity/bedienpost-dev#3]
try username "oo@uc.bar.com" mind the "'@uc." in there!

Observed message:
"Server not responding as expected. Please check the server and try again. Is your internet connection working?"
But since this domain does not even exist AT ALL, the error message is misleading. maybe indicate that the domain does not exist?

nb: found this after mistyping .com to .nl

**Comment by matthiasvdh** [comment]
Won't fix. If it is not Compass, we can't help you.
